[all]
depends = [
    "desktop",
    "alacritty",
    "bash",
]

[desktop]
depends = [
    "dunst",
    "fontconfig",
    "i3",
    "picom",
    "polybar",
    "rofi",
    "scripts",
    "stalonetray",
]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[bash.files]
"bash/.bashrc" = "~/.bashrc"
"bash/.bash_aliases" = "~/.bash_aliases"

[dunst.files]
"dunst" = "~/.config/dunst"

[fontconfig.files]
"fontconfig" = "~/.config/fontconfig"

[i3.files]
"i3" = "~/.config/i3"

[picom.files]
"picom/picom.conf" = "~/.config/picom.conf"

[polybar.files]
"polybar" = "~/.config/polybar"

[rofi.files]
"rofi" = "~/.config/rofi"

[scripts.files]
"scripts" = "~/.scripts"

[stalonetray.files]
"stalonetray/.stalonetrayrc" = "~/.stalonetrayrc"
