[all]
depends = [
    "desktop",
    "alacritty",
    "redshift",
    "vim",
    "zsh",
]

[desktop]
depends = [
    "dunst",
    "i3",
    "picom",
    "polybar",
    "rofi",
    "xorg",
]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[dunst.files]
"dunst" = "~/.config/dunst"

[i3.files]
"i3" = "~/.config/i3"

[picom.files]
"picom/picom.conf" = "~/.config/picom.conf"

[polybar.files]
"polybar" = "~/.config/polybar"

[redshift.files]
"redshift" = "~/.config/redshift"

[rofi.files]
"rofi" = "~/.config/rofi"

[vim.files]
"vim/.vimrc" = "~/.vimrc"

[xorg.files]
"xorg/.Xresources" = "~/.Xresources"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
