[all]
depends = [
    "desktop",
    "alacritty",
    "zsh",
]

[desktop]
depends = [
    "dunst",
    "i3",
    "picom",
    "polybar",
    "mons",
    "rofi",
    "scripts",
]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[dunst.files]
"dunst" = "~/.config/dunst"

[i3.files]
"i3" = "~/.config/i3"

[picom.files]
"picom/picom.conf" = "~/.config/picom.conf"

[polybar.files]
"polybar" = "~/.config/polybar"

[mons.files]
"mons" = "~/.config/mons"

[rofi.files]
"rofi" = "~/.config/rofi"

[scripts.files]
"scripts" = "~/.scripts"

[vim.files]
"vim/.vimrc" = "~/.vimrc"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
